version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.local
    container_name: projects
    ports:
      - 4000:3000
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    env_file:
      - .env
    environment:
      - GOPATH=/go
      - GOARCH=amd64
      - GOOS=linux
      - CGO_ENABLED=0
    command: "make serve"
    working_dir: /app
    networks:
      - project
  db:
    image: postgres
    networks:
      project:
        aliases:
          - database
    env_file:
      - .env
    ports:
      - "35432:5432"
  migrate:
    image: migrate/migrate
    container_name: migrate
    networks:
      - project
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "--",
        "/migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/postgres?sslmode=disable",
        "up",
      ]
    entrypoint: ""
    links:
      - db
networks:
  project:
